variables:
  system.debug: true
jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false

      - task: Npm@1
        displayName: 'Compile sources and run tests'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run test'
      
      # https://stackoverflow.com/questions/45602358/lcov-info-has-absolute-path-for-sf
      - script: |
          sed -i -- s/..\\..\\//g coverage/lcov.info && npm run coveralls
        displayName: 'Publish code coverage'  
        env:
          COVERALLS_SERVICE_NAME: $(COVERALLS_SERVICE_NAME)
          COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
          # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
          COVERALLS_GIT_COMMIT: $(Build.SourceVersion)
          # https://github.com/MicrosoftDocs/vsts-docs/issues/4259
          # https://stackoverflow.com/questions/16623835/remove-a-fixed-prefix-suffix-from-a-string-in-bash
          COVERALLS_GIT_BRANCH: $(Build.SourceBranch)
          COVERALLS_SERVICE_JOB_ID: $(Build.BuildId)
          CI_PULL_REQUEST: $(System.PullRequest.PullRequestNumber)

      - script: 'npm install -g vsce && vsce package'
        displayName: 'Build artifact'
      - task: CopyFiles@2
        inputs:
          contents: '*.vsix'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: vs-picgo-dev-build
trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
pr:
- dev*